### ISSUE TITLE
Suggestion / Issue

### ISSUE THREAD

**Issue by vrajroham** [secrethash/smsg#2]
Below line is executed when curl request is sent successfully to `API server (msg91)` and request returns the `request_id`. 

https://github.com/secrethash/smsg/blob/ac45c9050b0d1d5c69d43bd60758a01ba4594965/src/Smsg.php#L141

But there is little problem with this. If proper permissions are not set on `storage` directory, your request will be sent to the server but **Log will not be written** to log file due to permissions and **SMS is not sent/delivered**. I can provide steps to reproduce it.

### Steps to reproduce
* Change permission of storage directory so application can't write log to log file.
* Hit request to send SMS
* You **may** get `request id` on screen but SMS will not be sent.

This error occurs when proper permissions are not set. Cases when developers use CI/CD or devops and which rarely use `logs`. I spend whole day to solve this issue by step by step debugging. 

Hope you will address this issue. Also it will be useful for future users too.

**Comment by secrethash** [comment]
That is an issue to address. Working on it.

**Comment by secrethash** [comment]
First of all, Sorry, was on a vacation.

Addressing the Issue:
Is Log really necessary? I added it for testing purpose. Should I remove it?

**Comment by secrethash** [comment]
I added `Log::debug()` while developing, just changed it to `Log::info()` before shipping.

**Comment by vrajroham** [comment]
Even though you changed to info, it will try to log and fail. I would suggest to remove if not important for internal implementation.

**Comment by secrethash** [comment]
Yeah, removing it would be great as it's not needed for Internal Implementation and also doesn't have any future plans. 👍

**Comment by secrethash** [comment]
The Unnecessary Logs have been Removed. 
Commit: b8cb15b0cdec49c67daab00f673a668db6b18611

**Comment by vrajroham** [comment]
Hope it would be resolved. Closing #2
